name: Branch til dev

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/kabal-frontend:${{ github.sha }}
jobs:
  deploytodev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build
        run: |
          cd frontend
          npm i
          npm run build
      - name: Test Frontend
        run: |
          cd frontend
          npm test
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SESSION_KEY: ${{ secrets.klage-session-key }}
        run: |
          cat Dockerfile
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          SESSION_KEY: ${{ secrets.klage-session-key }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev.yaml
          VARS: nais/vars.yaml
  e2etest:
    name: E2E-test av deploy
    needs: deploytodev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1.1
      - name: Run acceptance tests
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          VAR: app=kabal,jobname=klage-job-${{ steps.generate-uuid.outputs.uuid }}
          TEAM: klage
          RESOURCE: deploy/e2ejob.yml
        timeout-minutes: 5
  deployprod:
    name: Deploy to prod-gcp
    needs: e2etest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/prod.yaml
          VARS: nais/prod.json
          SESSION_KEY: ${{ secrets.klage-session-key }}
      - name: Generate release version
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=7 HEAD)
          VERSION=$TIME-$COMMIT
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
