name: Prod-deploy

on:
  workflow_dispatch:

env:
  BASEIMAGE: docker.pkg.github.com/${{ github.repository }}/klage-oppgave
jobs:
  deployprod:
    name: Deploy to prod-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout code
      - name: Lag tag for image
        run: echo "TAG=$(git log -1 --pretty='%ad_%h' --date=format:'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Lag full image referanse
        run: echo "IMAGE=$BASEIMAGE:$TAG" >> $GITHUB_ENV
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/prod.yaml
          VARS: nais/prod.json
          SESSION_KEY: ${{ secrets.klage-session-key }}
      - name: Generate release version
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=7 HEAD)
          VERSION=$TIME-$COMMIT
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
